### ISSUE TITLE
Leaderboard changes

### ISSUE THREAD

**Issue by trrt-good** [Skparab1/pacman#17]
### Leaderboard is very cluttered
- The leaderboard gets flooded with scores because it seems to be storing multiple runs by the same user rather than only their high score. 14 unique players on the normal difficulty leaderboard but 64 entries. 
### No easy way to return to the pacman game after entering the leaderboard screen.
- The only way to return is to edit the link or keep pressing the back button, but since each leaderboard difficulty tab is a different link, you may have to press back many times. A direct button would be preferred.

**Comment by Skparab1** [comment]
Leaderboard - yes true and were probably gonna rework the leaderboard anyway cuz its kinda breachable
but yeah i just filtered out the bad entries so it shud be good now. I think its fine rn if it shows multiple runs of the same user but yeah if it gets too crowded then it can easily be filtered such that the only the highest score in the db is show for each user

return to pacman game - yeah i fixed that theres not a pacman button in the header and a back button near the level selector

thx for ur help

**Comment by trrt-good** [comment]
sounds good glad to help
