### ISSUE TITLE
Scroll bar appears because of the "unable to play audio" warning

### ISSUE THREAD

**Issue by trrt-good** [Skparab1/pacman#18]
The "unable to play audio" warning seems to push the top menu bar to the side which causes a horizontal scroll bar to appear which interferes with the left and right controls because the arrow keys also scroll the webpage back and fourth. 

https://user-images.githubusercontent.com/91699644/185039420-a08fff4c-eab5-4e77-8c37-c222e8256051.mp4

**Comment by Skparab1** [comment]
i see

fixed but it looks a bit cut off
i think thats fine
<img width="1024" alt="Screen Shot 2022-08-17 at 9 01 35 AM" src="https://user-images.githubusercontent.com/71990977/185188125-ea6ec9f7-ffd0-4496-b7ba-b2d6490890cd.png">

thanks
